variables:    
    GOPROJ: "github.com/RaveNoX/jenigma"    

stages:
- build

before_script:
- mkdir -p $GOPATH/src/$GOPROJ_BASE
- rmdir $GOPATH/src/$GOPROJ_BASE
- ln -s $(pwd) $GOPATH/src/$GOPROJ
- cd $GOPATH/src/$GOPROJ/
- go get -u github.com/golang/dep/cmd/dep
- dep ensure -v

cache:
    key: "${CI_COMMIT_REF_SLUG}"
    paths:
    - vendor/**    

build:
    stage: build
    tags:
    - docker
    - linux
    image: golang:latest
    script:
    - mkdir -p artifacts        
    - echo "Building for Linux"
    - GOOS=linux GOARCH=amd64 go build -o artifacts/jenigma .
    - echo "Building for MacOS (darwin)"
    - GOOS=darwin GOARCH=amd64 go build -o artifacts/jenigma_darwin .
    - echo "Building for Windows"
    - GOOS=windows GOARCH=amd64 go build -o artifacts/jenigma.exe .
    artifacts:
        paths:
        - artifacts/*

