variables:    
    GOPROJ: "github.com/RaveNoX/jenigma"    

stages:
- build

build:
    stage: build
    tags:
    - docker
    - linux
    image: golang:latest
    script:
    - mkdir -p artifacts        
    - echo "Building for Linux"
    - GOOS=linux GOARCH=amd64 go build -o artifacts/jenigma .
    - echo "Building for MacOS (darwin)"
    - GOOS=darwin GOARCH=amd64 go build -o artifacts/jenigma_darwin .
    - echo "Building for Windows"
    - GOOS=windows GOARCH=amd64 go build -o artifacts/jenigma.exe .
    artifacts:
        paths:
        - artifacts/*

