language: go

go:
- 1.x

install:
- mkdir -p artifacts

env:
  - GO111MODULE=on

script:
- GOARCH=amd64 GOOS=linux go build -o artifacts/jsonmerge
- GOARCH=amd64 GOOS=windows go build -o artifacts/jsonmerge.exe
- GOARCH=amd64 GOOS=darwin go build -o artifacts/jsonmerge_darwin
